language: node_js
node_js:
  - 4.6.2
  - 6.9.1
  - 6.10.2
  - 7.8.0
os:
  - linux
  - osx

before_install:
  - sh ./travis_scripts/before_install.sh

script:
  - "npm run hint"
  - "npm run test"
  - "npm run cover"

after_script: "cat ./coverage/lcov.info | coveralls"

matrix:
  allow_failures:
    - os: osx
